<a href="https://colab.research.google.com/github/domsjcsn/Linear-ALgebra---Python/blob/main/JOCSON-Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **FRANZ DOMINIQUE JOCSON**
## **BS ECE 201**
## **LINEAR ALGEBRA**

## ***LABORATORY 4: MATRICES***

In [100]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### **MATRICES**
<blockquote>One of the basics of modern computing is the use of matrices and its syllabary. From a huge number of complex and inter-related equations from 2D equations, matrices is considered a useful representation. 

## **TASK 1**
<blockquote>
Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2.Displays whether the matrix is square or non-square.
3.Displays whether the matrix is an empty matrix.
4.Displays if the matrix is an identity, ones, or zeros matrix

Use sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [101]:
def desc_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

## **MATRIX DECLARATION**

In [102]:
## Null Matrix
null_mat = np.array ([])

In [103]:
## Zero Matrix
zero_mat_sqr = np.zeros((3,3))

In [104]:
## Ones Matrix 
ones_mat_sqr = np.ones((3,3))

In [105]:
## Diagonal Matrix 
A = np.array([
    [3, 0, 0],
    [0, 3, 0],
    [0, 0, 9]          

])


In [106]:
## Identity Matrix
# np.identity(3)

In [107]:
## Upper Triangular Matrix
B = np.array([
    [1, 8, 1],
    [0, 4, 7],
    [0, 0, 9]         
])

In [108]:
#Lower Triangular Matrix
C = np.array([
    [2, 0, 0],
    [6, 4, 0],
    [7, 7, 1]          

])

## ***TEST AREA***

In [109]:
## Null Matrix
desc_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



In [110]:
## Zero Matrix
desc_mat(zero_mat_sqr)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2



In [111]:
## Ones Matrix
desc_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(3, 3)
Rank:	2



In [112]:
## Diagonal Matrix
desc_mat(A)

Matrix:
[[3 0 0]
 [0 3 0]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



In [113]:
## Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
## Upper Triangular Matrix
desc_mat(B)

Matrix:
[[1 8 1]
 [0 4 7]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



In [115]:
## Lower Triangular Matrix
desc_mat(C)

Matrix:
[[2 0 0]
 [6 4 0]
 [7 7 1]]

Shape:	(3, 3)
Rank:	2



## **TASK 2**
<blockquote>
Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.

2. Returns the sum of the matrices.

3. Returns the differen of the matrices.

4. Returns the element-wise multiplication of the matrices.

5. Returns the element-wise division of the matrices.

Use sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [116]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [117]:
## Addition
A = np.array([
   [3,2,9,],
   [3,1,7],
   [8,2,8],
         
])
B = np.array([
   [4,3,4],
   [1,5,1],
   [2,2,2]
])


In [118]:
## Subtraction
D = np.array([
    [5,2,2],
    [4,6,6],
    [1,8,1]
])
E = np.array([
    [8,6,9],
    [7,1,7],
    [1,1,7]
])

In [119]:
## Element-Wise Multiplication
F = np.array([
    [3,2,3],
    [5,3,5],
    [6,7,6]
])
G = np.array([
    [4,3,4],
    [1,1,7],
    [0,0,6]
])

In [120]:
## Element-Wise Division
H = np.array([
    [11,13,21],
    [16,8,0],
    [21,24,11]
])
I = np.array([
    [3,8,5],
    [8,5,2],
    [11,15,2]
])

## **TEST AREA**

In [121]:
## Addition
C = A+B 
mat_operations(C)

Matrix:
[[ 7  5 13]
 [ 4  6  8]
 [10  4 10]]

Shape:	(3, 3)
Rank:	2



In [122]:
np.add(A,B)

array([[ 7,  5, 13],
       [ 4,  6,  8],
       [10,  4, 10]])

In [123]:
## Subtraction
S = D-E
mat_operations(S)

Matrix:
[[-3 -4 -7]
 [-3  5 -1]
 [ 0  7 -6]]

Shape:	(3, 3)
Rank:	2



In [124]:
np.subtract(D,E)

array([[-3, -4, -7],
       [-3,  5, -1],
       [ 0,  7, -6]])

In [125]:
## element-wise multiplication
M = F*G
mat_operations(M)

Matrix:
[[12  6 12]
 [ 5  3 35]
 [ 0  0 36]]

Shape:	(3, 3)
Rank:	2



In [126]:
np.multiply(F,G)

array([[12,  6, 12],
       [ 5,  3, 35],
       [ 0,  0, 36]])

In [127]:
2*F

array([[ 6,  4,  6],
       [10,  6, 10],
       [12, 14, 12]])

In [128]:
4*G

array([[16, 12, 16],
       [ 4,  4, 28],
       [ 0,  0, 24]])

In [129]:
## element-wise division
V = H/I
mat_operations(V)

Matrix:
[[3.66666667 1.625      4.2       ]
 [2.         1.6        0.        ]
 [1.90909091 1.6        5.5       ]]

Shape:	(3, 3)
Rank:	2



In [130]:
np.divide(H,I)

array([[3.66666667, 1.625     , 4.2       ],
       [2.        , 1.6       , 0.        ],
       [1.90909091, 1.6       , 5.5       ]])

In [131]:
H/5

array([[2.2, 2.6, 4.2],
       [3.2, 1.6, 0. ],
       [4.2, 4.8, 2.2]])

In [132]:
1/I

array([[0.33333333, 0.125     , 0.2       ],
       [0.125     , 0.2       , 0.5       ],
       [0.09090909, 0.06666667, 0.5       ]])

## **CONCLUSION**
<blockquote>
This laboratory activity helped the students to widen their knowledge about Matrices and operations and how can it be solved in Python. Like what our professor taught us, the codes used to define matrices are different. Utilizing matrices and operations can help us in solving complex equations and problems, thus making our work lighter and easier. 